# Generated by Django 5.1.2 on 2024-10-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ClubModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=14, verbose_name='Ваканс')),
                ('cources', models.TextField(max_length=15, verbose_name='Курс')),
                ('payment', models.IntegerField(max_length=24, verbose_name='цена')),
                ('place', models.CharField(max_length=29, verbose_name='место')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubapp.category', verbose_name='выберите категорию')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
