# Generated by Django 5.1.2 on 2024-11-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание гайда')),
                ('image', models.CharField(max_length=500, verbose_name='URL фото')),
            ],
            options={
                'verbose_name': 'ГАйд',
                'verbose_name_plural': 'Гайды',
            },
        ),
    ]
