# Generated by Django 5.1.2 on 2024-11-02 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0003_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации:'),
        ),
        migrations.AlterField(
            model_name='clubmodels',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации:'),
        ),
    ]
