# Generated by Django 5.1.2 on 2024-11-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0004_guide_date_alter_clubmodels_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodels',
            name='brief_description',
            field=models.CharField(default='None', max_length=83, verbose_name='краткое описание:'),
        ),
        migrations.AddField(
            model_name='clubmodels',
            name='full_description',
            field=models.TextField(default='None', max_length=2200, verbose_name='Описание:'),
        ),
        migrations.AddField(
            model_name='clubmodels',
            name='groups',
            field=models.CharField(default='None', max_length=500, verbose_name='группы'),
        ),
        migrations.AddField(
            model_name='clubmodels',
            name='members',
            field=models.IntegerField(default=0, verbose_name='участники'),
        ),
        migrations.AddField(
            model_name='clubmodels',
            name='schedule',
            field=models.CharField(default=1, max_length=2200, verbose_name='график'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubmodels',
            name='seats',
            field=models.IntegerField(default=0, verbose_name='места'),
        ),
        migrations.AlterField(
            model_name='clubmodels',
            name='cources',
            field=models.CharField(max_length=15, verbose_name='Курс'),
        ),
    ]
