# Generated by Django 5.1.3 on 2024-11-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0005_clubmodels_brief_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
