# Generated by Django 5.1.3 on 2024-11-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0006_delete_guide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmodels',
            options={'verbose_name': 'Клуб', 'verbose_name_plural': 'Клубы'},
        ),
        migrations.AddField(
            model_name='clubmodels',
            name='image',
            field=models.CharField(default='https://w7.pngwing.com/pngs/537/283/png-transparent-the-columbus-metropolitan-club-service-business-sales-building-none-building-text-service.png', max_length=10000, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='clubmodels',
            name='brief_description',
            field=models.CharField(default='Нету', max_length=83, verbose_name='Краткое описание:'),
        ),
        migrations.AlterField(
            model_name='clubmodels',
            name='full_description',
            field=models.TextField(default='Нету', max_length=2200, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='clubmodels',
            name='groups',
            field=models.CharField(default='Нету', max_length=500, verbose_name='группы'),
        ),
        migrations.AlterField(
            model_name='clubmodels',
            name='payment',
            field=models.IntegerField(default='Бесплатно', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='clubmodels',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Клуб'),
        ),
    ]
